# Generated by Django 5.0.1 on 2024-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_marker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
