# Generated by Django 5.0.6 on 2024-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_marker_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
    ]
