# Generated by Django 5.0.6 on 2024-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_leaveaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marker_count',
            field=models.IntegerField(default=0),
        ),
    ]
